// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:carbu_track/src/features/home/favorite/infrastructure/domain/favorite.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavoriteAdapter());
  }
}
